name: Build an image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: pe-arc-runner-shared-npd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
              
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}"    
          
      - name: Build and push staging images
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: ${{secrets.ACR_NAME}}/ratings-web:v1
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          build-args: GITHUB_PAT=${{ secrets.GH_IAC_PAT }}
          
      
